name: Node.js CI

on:
  repository_dispatch:
    types: pull-serial-vault

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: CanonicalLtd/serial-vault
      - name: Create report file
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        id: cpr
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "WIP: Automated javascript build"
          title: '[WIP] Add builded javascript/css files'
